server:
  port: 8081
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-8888:8888/eureka
  instance:
    hostname: service-verification-code
spring:
  application:
    name: service-verification-code
