eureka:
  client:
    service-url:
      defaultZone: http://eureka-8888:8888/eureka
---
spring:
  profiles: v1
  application:
    name: gray-provider
server:
  port: 9001
eureka:
  instance:
    metadata-map:
      version: v1
---
spring:
  profiles: v2
  application:
    name: gray-provider
server:
  port: 9002
eureka:
  instance:
    metadata-map:
      version: v2
