server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://eureka-8888:8888/eureka
    register-with-eureka: false
    fetch-registry: false
    # 客户端拉取 2次服务/min  （服务预算）
    registry-fetch-interval-seconds: 30
  instance:
    hostname: eureka-8888
  server:
    # 自我保护，看服务多少。
#    enable-self-preservation: false
    # 自我保护阈值
#    renewal-percent-threshold: 0.85
    # 剔除服务时间间隔
#    eviction-interval-timer-in-ms: 1000
    # 关闭从readOnly读注册表
    use-read-only-response-cache: false
    # readWrite 和 readOnly 同步时间间隔。
#    response-cache-update-interval-ms: 1000

